/** متن‌های صفحهٔ تحلیل آفلاین — تنها منبع حقیقت برای هر دو زبان */
import type { Dict } from '../../i18n';

export const offlineDict = {
  // تب‌ها
  tabAnalysis: { fa: 'تحلیل جدید', en: 'New Analysis' },
  tabResults: { fa: 'نتایج', en: 'Results' },
  tabVisualization: { fa: 'تصویرسازی ضایعات', en: 'Lesion Visualization' },
  tabHistory: { fa: 'تاریخچه', en: 'History' },
  tabAllAnalyses: { fa: 'آرشیو تحلیل‌ها', en: 'All Analyses' },
  selectClientFirst: { fa: 'ابتدا یک مشتری انتخاب کنید', en: 'Select a client first' },
  selectClientHint: {
    fa: 'از تب «تحلیل جدید» مشتری را انتخاب کنید تا تاریخچهٔ مراجعاتش اینجا دیده شود.',
    en: 'Pick a client in the New Analysis tab to see their visit history here.',
  },
  noHistory: { fa: 'تاریخچه‌ای برای این مشتری ثبت نشده', en: 'No history for this client yet' },
  historyFor: { fa: 'تاریخچه مراجعات', en: 'Visit history for' },
  // بنر موتور / مشاهده
  offlineBanner: { fa: 'تحلیل کاملاً آفلاین — بدون نیاز به اینترنت', en: 'Fully offline — no internet required' },
  enginePython: { fa: 'موتور Python (OpenCV) در دسترس', en: 'Python engine (OpenCV) available' },
  engineBrowser: { fa: 'موتور مرورگر (بدون نیاز به اینترنت)', en: 'Browser engine (no internet required)' },
  engineLocalModel: { fa: 'تحلیل با مدل یادگیری محلی انجام شد', en: 'Analyzed with local learning model' },
  enginePythonFallback: {
    fa: 'Python در دسترس نبود — از موتور مرورگر استفاده شد',
    en: 'Python unavailable — used browser engine',
  },
  viewMode: { fa: 'حالت مشاهده', en: 'View Mode' },
  delete: { fa: 'حذف', en: 'Delete' },
  close: { fa: 'بستن', en: 'Close' },
  deleteConfirm: { fa: 'آیا از حذف این تحلیل اطمینان دارید؟', en: 'Delete this analysis?' },

  // تب تحلیل
  searchClient: { fa: 'جستجوی مشتری...', en: 'Search client...' },
  eligibleClients: { fa: 'مشتریان واجد شرایط این ماژول', en: 'Clients eligible for this module' },
  endVisit: { fa: 'پایان مراجعه', en: 'End visit' },
  endVisitHint: {
    fa: 'نوبت فقط با این دکمه بسته می‌شود. تا قبل از آن، ماژول‌های دیگر روی همین مراجعه کار می‌کنند.',
    en: 'The appointment closes only with this button. Until then, other modules can continue on the same visit.',
  },
  noEligibleClients: { fa: 'مشتری با نوبت آتی یافت نشد', en: 'No clients with upcoming sessions' },
  selectImage: { fa: 'انتخاب تصویر', en: 'Select Image' },
  noGalleryImages: {
    fa: 'تصویری در گالری این مشتری وجود ندارد',
    en: "No images in this client's gallery",
  },
  analyzing: { fa: 'در حال تحلیل آفلاین...', en: 'Analyzing offline...' },
  analyze: { fa: 'تحلیل آفلاین', en: 'Offline Analysis' },
  selectImageError: { fa: 'لطفا یک تصویر انتخاب کنید', en: 'Please select an image' },
  analysisFailed: { fa: 'خطا در تحلیل', en: 'Analysis failed' },
  offlineError: { fa: 'خطا در تحلیل آفلاین', en: 'Offline analysis error' },

  // نتایج
  hairDensity: { fa: 'تراکم مو', en: 'Hair Density' },
  scalpCondition: { fa: 'وضعیت پوست سر', en: 'Scalp Condition' },
  oiliness: { fa: 'چربی', en: 'Oiliness' },
  dryness: { fa: 'خشکی', en: 'Dryness' },
  dandruff: { fa: 'شوره', en: 'Dandruff' },
  redness: { fa: 'قرمزی', en: 'Redness' },
  specializedIndicators: { fa: 'شاخص‌های تخصصی‌تر', en: 'Specialized Indicators' },
  shine: { fa: 'براقی/سبوره سطحی', en: 'Surface shine/sebum' },
  patchiness: { fa: 'لکه‌ای بودن ریزش', en: 'Patchiness' },
  pigmentation: { fa: 'ناهمگونی رنگدانه', en: 'Pigmentation irregularity' },
  hairThickness: { fa: 'ضخامت نسبی تار مو', en: 'Relative hair thickness' },
  specializedHint: {
    fa: 'این شاخص‌ها تخمینی و مبتنی بر تحلیل هوش مصنوعی هستند، نه تشخیص بالینی قطعی.',
    en: 'These indicators are AI-based estimates, not a definitive clinical diagnosis.',
  },
  heuristicExperimentalNote: {
    fa: 'موتور تحلیل آفلاین بر پایهٔ آستانه‌های تجربی و غیرکالیبره‌شدهٔ بالینی روی رنگ/بافت پیکسل کار می‌کند — دقتش را نباید معادل تشخیص پزشکی یا دستگاه تریکوسکوپ دانست.',
    en: 'The offline engine relies on experimental, non clinically-calibrated pixel color/texture thresholds — its accuracy should not be treated as equivalent to a medical diagnosis or trichoscope device.',
  },

  screeningDisclaimer: {
    fa: 'پیشنهاد غربالگری خودکار — غیرتشخیصی. جایگزین معاینهٔ متخصص نیست.',
    en: 'Automated screening suggestion — non-diagnostic. Not a substitute for specialist examination.',
  },
  sourceBadgeAi: {
    fa: 'تحلیل آنلاین (مدل زبانی تصویری)',
    en: 'Online analysis (vision language model)',
  },
  sourceBadgeOffline: {
    fa: 'تحلیل آفلاین / قانون‌محور یا مدل محلی',
    en: 'Offline / rule-based or local model',
  },
  heuristicFilledHint: {
    fa: 'یافته‌های بالینی از قوانین آستانه‌ای پر شده‌اند چون موتور شناسهٔ کاتالوگ برنگرداند.',
    en: 'Clinical findings were filled from threshold rules because the engine returned no catalog IDs.',
  },
  hairLoss: { fa: 'ریزش مو', en: 'Hair Loss' },
  engine: { fa: 'موتور:', en: 'Engine:' },
  lesions: { fa: 'ضایعات', en: 'Lesions' },
  noLesions: { fa: 'مورد خاصی شناسایی نشد', en: 'No specific findings' },
  clinicalObservations: { fa: 'مشاهدات کلینیکی', en: 'Clinical Observations' },
  noObservations: { fa: 'تشخیص کلینیکی ثبت نشد', en: 'No clinical diagnoses recorded' },
  observationsAutoHint: {
    fa: 'گزینه‌های تشخیص‌داده‌شده توسط تحلیل به‌صورت خودکار برجسته شده‌اند.',
    en: 'Diagnoses detected by the analysis are highlighted automatically.',
  },
  selectDiagnoses: { fa: 'انتخاب تشخیص‌های کلینیکی', en: 'Select clinical diagnoses' },
  overallHealthScore: { fa: 'امتیاز کلی سلامت پوست سر', en: 'Overall Scalp Health Score' },
  overallHealthScoreHint: {
    fa: 'بر اساس تراکم مو و شاخص‌های وضعیت پوست سر محاسبه می‌شود.',
    en: 'Computed from hair density and scalp condition metrics.',
  },
  metricsRadar: { fa: 'نمای کلی شاخص‌ها (رادار)', en: 'Metrics Overview (Radar)' },
  lesionsDistribution: { fa: 'خلاصه کلی ضایعات شناسایی‌شده', en: 'Overall Detected Findings Summary' },
  lesionsByRegion: { fa: 'ضایعات بر اساس ناحیه سر', en: 'Findings by Scalp Region' },
  lesionsByRegionHint: { fa: 'هر نوع ضایعه در هر ناحیه فقط یک‌بار نمایش داده می‌شود؛ تعداد نواحی/تصاویر درگیر کنار آن آمده است.', en: 'Each lesion type appears once per region; affected photo-region count is shown beside it.' },
  unknownRegion: { fa: 'ناحیه نامشخص', en: 'Unknown region' },
  affectedAreas: { fa: 'ناحیه/تصویر', en: 'photo-regions' },
  keyFindingsChart: { fa: 'نمودار هوشمند یافته‌های کلیدی', en: 'AI Key Findings Map' },
  keyFindingsChartHint: { fa: 'سه شاخص مهم‌تر با شدت و سطح آن‌ها نمایش داده شده‌اند.', en: 'The three most important indicators are shown with their intensity.' },
  lesionsByRegionChartHint: { fa: 'هر ناحیه با نمودار اختصاصی و ضایعات یکتای همان ناحیه نمایش داده می‌شود.', en: 'Each scalp region has its own chart with unique findings.' },
  severityHigh: { fa: 'شدت بالا', en: 'High severity' },
  severityMedium: { fa: 'شدت متوسط', en: 'Medium severity' },
  severityLow: { fa: 'شدت پایین', en: 'Low severity' },
  noRegionData: { fa: 'داده‌ای برای نمودار ناحیه‌ای وجود ندارد', en: 'No regional chart data available' },
  confidence: { fa: 'اطمینان', en: 'confidence' },
  clinicalConditions: { fa: 'بیماری‌ها و الگوهای احتمالی', en: 'Possible conditions and patterns' },
  trichoscopyFindings: { fa: 'نشانه‌های مشاهده‌شده تریکوسکوپی', en: 'Observed trichoscopy findings' },
  observedFinding: { fa: 'نشانه مشاهده‌شده', en: 'Observed sign' },
  possibleCondition: { fa: 'مورد احتمالی', en: 'Possible condition' },
  requiresConfirmation: { fa: 'نیازمند تأیید متخصص/آزمایش', en: 'Requires specialist/lab confirmation' },
  finalResult: { fa: 'نتیجه نهایی', en: 'Final result' },
  allLenses: { fa: 'همه لنزها', en: 'All lenses' },
  lensFilter: { fa: 'لنز:', en: 'Lens:' },
  metricsChart: { fa: 'نمودار شاخص‌ها', en: 'Metrics Chart' },
  recommendations: { fa: 'پیشنهادات', en: 'Recommendations' },
  performAnalysisFirst: { fa: 'ابتدا یک تحلیل انجام دهید', en: 'Perform an analysis first' },

  // هدر / یافته‌ها / مقایسه / گزارش
  keyFindings: { fa: 'یافته‌های کلیدی', en: 'Key Findings' },
  keyFindingsHint: {
    fa: 'مهم‌ترین موارد نیازمند توجه در این تحلیل',
    en: 'Top issues that need attention in this analysis',
  },
  viewImage: { fa: 'مشاهده تصویر', en: 'View image' },
  reportClient: { fa: 'مشتری', en: 'Client' },
  reportDate: { fa: 'تاریخ', en: 'Date' },
  unknownClient: { fa: 'مشتری نامشخص', en: 'Unknown client' },
  comparePrevious: { fa: 'مقایسه با جلسه قبل', en: 'Compared with previous session' },
  noPreviousSession: {
    fa: 'جلسهٔ قبلی برای مقایسه ثبت نشده است.',
    en: 'No previous session available for comparison.',
  },
  hoverTrendHint: {
    fa: 'با حرکت موس روی نمودار، درصدهای همان جلسه نمایش داده می‌شود',
    en: 'Hover the chart to preview that session’s percentages',
  },
  pastSessions: { fa: 'جلسات قبلی', en: 'Past sessions' },
  improved: { fa: 'بهبود', en: 'Improved' },
  worsened: { fa: 'تضعیف', en: 'Worsened' },
  unchanged: { fa: 'بدون تغییر', en: 'Unchanged' },
  printReport: { fa: 'چاپ رنگی', en: 'Color print' },
  savePdf: { fa: 'ذخیره PDF', en: 'Save PDF' },
  pdfSaved: { fa: 'PDF ذخیره شد', en: 'PDF saved' },
  pdfSaveFailed: { fa: 'ذخیره PDF ناموفق بود', en: 'Failed to save PDF' },
  chartsSection: { fa: 'نمودارها', en: 'Charts' },
  preparingReport: { fa: 'در حال آماده‌سازی گزارش و نمودارها...', en: 'Preparing report and charts...' },
  sessionDetails: { fa: 'جزئیات جلسات', en: 'Session details' },
  latestSession: { fa: 'مقادیر آخرین جلسه', en: 'Latest session values' },
  shareReport: { fa: 'اشتراک', en: 'Share' },
  reportTitle: { fa: 'گزارش تحلیل پوست سر', en: 'Scalp Analysis Report' },
  reportTitleAi: { fa: 'گزارش تحلیل هوش مصنوعی پوست سر', en: 'AI Scalp Analysis Report' },
  shareCopied: { fa: 'متن گزارش در کلیپ‌بورد کپی شد', en: 'Report text copied to clipboard' },
  shareFailed: { fa: 'اشتراک‌گذاری انجام نشد', en: 'Sharing failed' },
  printBlocked: {
    fa: 'پنجرهٔ چاپ مسدود شد — اجازهٔ پاپ‌آپ را فعال کنید',
    en: 'Print window blocked — allow pop-ups',
  },
  recUrgent: { fa: 'فوری', en: 'Urgent' },
  recCare: { fa: 'مراقبت', en: 'Care' },
  recFollowup: { fa: 'پیگیری', en: 'Follow-up' },
  recommendationsHint: {
    fa: 'پیشنهادات بر اساس شدت شاخص‌ها اولویت‌بندی شده‌اند؛ موارد زمینه‌ای از پرسشنامه پزشکی هم اضافه می‌شوند.',
    en: 'Recommendations are prioritized by metric severity; questionnaire context may add clinical notes.',
  },
  clinicalFlags: { fa: 'پرچم‌های بالینی (پرسشنامه)', en: 'Clinical flags (questionnaire)' },
  clinicalFlagsHint: {
    fa: 'این پرچم‌ها از پرسشنامه پزشکی می‌آیند و امتیازهای اندازه‌گیری تصویر را تغییر نمی‌دهند.',
    en: 'These flags come from the medical questionnaire and do not change image measurement scores.',
  },
  interpretationConfidence: { fa: 'اطمینان تفسیر زمینه‌ای', en: 'Context interpretation confidence' },

  // امتیاز سلامت
  healthExcellent: { fa: 'عالی', en: 'Excellent' },
  healthGood: { fa: 'خوب', en: 'Good' },
  healthFair: { fa: 'متوسط', en: 'Fair' },
  healthNeedsAttention: { fa: 'نیازمند توجه', en: 'Needs attention' },

  // متریک‌های کوتاه نمودار
  metricDensity: { fa: 'تراکم', en: 'Density' },
  metricOiliness: { fa: 'چربی', en: 'Oiliness' },
  metricDryness: { fa: 'خشکی', en: 'Dryness' },
  metricDandruff: { fa: 'شوره', en: 'Dandruff' },
  metricRedness: { fa: 'قرمزی', en: 'Redness' },
  metricShine: { fa: 'براقی', en: 'Shine' },
  metricPatchiness: { fa: 'لکه‌ای بودن', en: 'Patchiness' },
  metricPigmentation: { fa: 'رنگدانه', en: 'Pigmentation' },
  densityShort: { fa: 'تراکم', en: 'density' },

  // تصویرسازی
  download: { fa: 'دانلود', en: 'Download' },
  visualizationHint: {
    fa: 'کادرهای رنگی مربعی محل ضایعات تشخیص‌داده‌شده را نشان می‌دهند.',
    en: 'Colored square boxes mark detected lesion areas on the image.',
  },

  // تاریخچه / آرشیو
  selectClient: { fa: 'مشتری انتخاب کنید', en: 'Select a client' },
  trendOverTime: { fa: 'روند تغییرات در طول زمان', en: 'Trend Over Time' },
  search: { fa: 'جستجو...', en: 'Search...' },

  // یادگیری ماشین
  webStorageWarning: {
    fa: 'در نسخهٔ وب، مدل و نمونه‌های آموزشی در همین مرورگر ذخیره می‌شوند و با پاک شدن دادهٔ مرورگر از بین می‌روند. برای ذخیرهٔ دائمی از نسخهٔ دسکتاپ استفاده کنید.',
    en: 'In the web version, the model and training samples are stored in this browser only and will be lost if browser data is cleared. Use the desktop app for persistent storage.',
  },
  localLearningModel: { fa: 'مدل یادگیری محلی', en: 'Local Learning Model' },
  totalSamples: { fa: 'کل نمونه‌ها', en: 'Total samples' },
  aiAutoLabeled: { fa: 'برچسب خودکار AI', en: 'AI auto-labeled' },
  expertLabeled: { fa: 'برچسب متخصص', en: 'Expert-labeled' },
  unusedInTraining: { fa: 'استفاده‌نشده در آموزش', en: 'Not yet used in training' },
  currentModelVersion: { fa: 'آخرین آموزش — نسخه:', en: 'Last training — version:' },
  trainedOn: { fa: 'با', en: 'with' },
  samplesOn: { fa: 'نمونهٔ واجد شرایط در', en: 'eligible samples on' },
  modelBelowStandard: {
    fa: 'این مدل با استاندارد فعلی آموزش سازگار نیست (حداقل ۲۰ نمونه لازم است یا معماری قدیمی است). برای تحلیل حرفه‌ای دوباره آموزش دهید.',
    en: 'This model does not meet the current training standard (need ≥20 samples, or architecture is outdated). Retrain for professional use.',
  },
  modelCatalogUpdated: {
    fa: 'کاتالوگ مشاهدات کلینیکی به‌روز شده — مدل قبلی باید دوباره آموزش داده شود.',
    en: 'Clinical observation catalog was updated — retrain the previous model.',
  },
  trainingLoss: { fa: 'خطای آموزش (loss):', en: 'Training loss:' },
  valLoss: { fa: 'خطای اعتبارسنجی', en: 'val loss' },
  maeScores: { fa: 'میانگین خطای امتیازها (MAE):', en: 'Score MAE:' },
  valMae: { fa: 'MAE اعتبارسنجی', en: 'val MAE' },
  obsF1: { fa: 'F1 تشخیص‌ها:', en: 'Observation F1:' },
  holdoutMae: { fa: 'MAE دادهٔ hold-out:', en: 'Hold-out MAE:' },
  holdoutF1: { fa: 'F1 hold-out:', en: 'Hold-out F1:' },
  featureVersionLabel: { fa: 'نسخهٔ فیچر مدل:', en: 'Model feature version:' },
  modelIncludesQuestionnaire: { fa: 'شامل پرسشنامه', en: 'includes questionnaire' },
  v4Experiment: { fa: 'آزمایش v4', en: 'v4 experiment' },
  v4GateStatus: { fa: 'آمادگی آزمایش پرسشنامه (v4)', en: 'Questionnaire experiment (v4) readiness' },
  v4GateReady: {
    fa: 'حد نصاب برقرار است — در آموزش بعدی تصویر-فقط با v4 روی holdout مقایسه می‌شود.',
    en: 'Threshold met — next training will compare image-only vs v4 on holdout.',
  },
  eligibleSamples: { fa: 'واجد شرایط آموزش', en: 'Eligible for training' },
  approvedAi: { fa: 'AI تأییدشده', en: 'Approved AI' },
  pendingAi: { fa: 'AI در انتظار تأیید', en: 'AI pending approval' },
  approveForTraining: { fa: 'تأیید برای آموزش', en: 'Approve for training' },
  revokeApproval: { fa: 'لغو تأیید', en: 'Revoke approval' },
  approved: { fa: 'تأییدشده', en: 'Approved' },
  datasetQuality: { fa: 'کیفیت دیتاست', en: 'Dataset quality' },
  architecture: { fa: 'معماری:', en: 'Architecture:' },
  epochsRun: { fa: 'تعداد epoch:', en: 'Epochs run:' },
  modelHistory: { fa: 'تاریخچه نسخه‌ها', en: 'Version history' },
  compareEngines: { fa: 'مقایسه مدل و تحلیل عادی', en: 'Compare model vs heuristic' },
  compareHint: {
    fa: 'یک نمونهٔ آموزشی انتخاب کنید تا اختلاف مدل محلی با تحلیل عادی را ببینید.',
    en: 'Pick a training sample to compare the local model against the heuristic engine.',
  },
  runCompare: { fa: 'اجرای مقایسه', en: 'Run comparison' },
  heuristicCol: { fa: 'تحلیل عادی', en: 'Heuristic' },
  modelCol: { fa: 'مدل محلی', en: 'Local model' },
  avgDiff: { fa: 'میانگین اختلاف', en: 'Average difference' },
  noModelForCompare: { fa: 'ابتدا مدل را آموزش دهید', en: 'Train a model first' },
  modelOutdated: {
    fa: 'این مدل با نسخهٔ قدیمی‌تر شاخص‌ها آموزش دیده — لطفاً دوباره آموزش دهید.',
    en: 'This model was trained with an older feature set — please retrain it.',
  },
  trainModel: { fa: 'آموزش حرفه‌ای مدل', en: 'Professional model training' },
  useLocalModel: {
    fa: 'استفاده از مدل محلی برای تحلیل‌های آفلاین بعدی',
    en: 'Use local model for future offline analyses',
  },
  deleteModel: { fa: 'حذف مدل', en: 'Delete model' },
  trainProgressHint: {
    fa: 'آموزش با early stopping، اعتبارسنجی بر اساس مشتری و ارزیابی hold-out انجام می‌شود.',
    en: 'Training uses early stopping, client-based validation, and hold-out evaluation.',
  },
  expertManualLabeling: { fa: 'برچسب‌گذاری دستی متخصص', en: 'Expert Manual Labeling' },
  expertLabelHint: {
    fa: 'یک تصویر از گالری مشتری انتخاب کنید، روی عکس کلیک کنید تا بزرگ شود، با کشیدن موس کادر دور ضایعه بکشید و برچسب بزنید. نمونه‌های متخصص وزن بالاتر در آموزش دارند.',
    en: 'Select a client image, click to enlarge, drag to box lesions and label them. Expert samples get higher weight in training.',
  },
  clickToEnlarge: { fa: 'کلیک برای بزرگ‌نمایی و رسم کادر', en: 'Click to enlarge and draw boxes' },
  drawLesionHint: {
    fa: 'با نگه داشتن و کشیدن موس، کادر مستطیلی دور ضایعه بکشید؛ سپس برچسب را انتخاب کنید.',
    en: 'Click and drag to draw a rectangle around a lesion, then pick its label.',
  },
  pickLesionLabel: { fa: 'برچسب این ضایعه را انتخاب کنید', en: 'Select a label for this lesion' },
  cancelBox: { fa: 'لغو کادر', en: 'Cancel box' },
  removeBox: { fa: 'حذف کادر', en: 'Remove box' },
  drawnLesionBoxes: { fa: 'کادرهای مشخص‌شده توسط متخصص', en: 'Expert-drawn lesion boxes' },
  noDrawnBoxes: { fa: 'هنوز کادری رسم نشده — روی تصویر کلیک کنید', en: 'No boxes yet — click the image to start' },
  selectClientOption: { fa: 'انتخاب مشتری', en: 'Select client' },
  searchOrSelectClient: { fa: 'جستجو یا انتخاب مشتری...', en: 'Search or select client...' },
  recentClients: { fa: '۱۰ مشتری اخیر', en: 'Recent 10 clients' },
  noClientsFound: { fa: 'مشتری‌ای یافت نشد', en: 'No clients found' },
  clientSelected: { fa: 'مشتری انتخاب شد', en: 'Client selected' },
  selectImageOption: { fa: 'انتخاب تصویر', en: 'Select image' },
  hairLossLevel: { fa: 'سطح ریزش مو', en: 'Hair loss level' },
  mild: { fa: 'خفیف', en: 'Mild' },
  moderate: { fa: 'متوسط', en: 'Moderate' },
  severe: { fa: 'شدید', en: 'Severe' },
  densityLevel: { fa: 'سطح تراکم', en: 'Density level' },
  low: { fa: 'کم', en: 'Low' },
  medium: { fa: 'متوسط', en: 'Medium' },
  high: { fa: 'زیاد', en: 'High' },
  saveLabel: { fa: 'ذخیرهٔ برچسب', en: 'Save label' },
  saveCorrection: { fa: 'ذخیرهٔ تصحیح متخصص', en: 'Save specialist correction' },
  cancelEdit: { fa: 'لغو ویرایش', en: 'Cancel edit' },
  editSample: { fa: 'ویرایش', en: 'Edit' },
  editingAiSample: {
    fa: 'در حال ویرایش نظر AI — پس از ذخیره به‌عنوان برچسب متخصص ثبت می‌شود.',
    en: 'Editing AI label — after save it becomes an expert-corrected sample.',
  },
  editingExpertSample: {
    fa: 'در حال ویرایش برچسب متخصص.',
    en: 'Editing an expert label.',
  },
  autoSuggest: { fa: 'پیشنهاد خودکار (heuristic)', en: 'Auto-suggest (heuristic)' },
  recentSamples: { fa: 'نمونه‌های آموزشی اخیر', en: 'Recent training samples' },
  sourceExpert: { fa: 'متخصص', en: 'Expert' },
  sourceHeuristic: { fa: 'heuristic', en: 'heuristic' },
  used: { fa: 'استفاده‌شده', en: 'used' },

  // استخر تصاویر آموزشی (بدون مشتری واقعی)
  trainingGalleryTitle: { fa: 'استخر تصاویر آموزشی', en: 'Training Pool' },
  trainingPoolGalleryTitle: { fa: 'گالری استخر آموزشی', en: 'Training Pool Gallery' },
  labelingSourceTitle: { fa: 'منبع تصاویر برچسب‌گذاری', en: 'Labeling image source' },
  clientGallerySourceHint: { fa: 'تصاویر مشتریان واقعی', en: 'Real client images' },
  trainingPoolSourceHint: { fa: 'تصاویر فعال برای آموزش', en: 'Active training images' },
  trainingPoolGallerySourceHint: { fa: 'تصاویر تکمیل‌شده', en: 'Completed training images' },
  completedTrainingItems: { fa: 'تصاویر ذخیره‌شده و تکمیل‌شده', en: 'Saved and completed training images' },
  advancedFilters: { fa: 'فیلترهای پیشرفته', en: 'Advanced filters' },
  dateFrom: { fa: 'از تاریخ ورود', en: 'Entered from' },
  dateTo: { fa: 'تا تاریخ ورود', en: 'Entered to' },
  clearDates: { fa: 'پاک کردن تاریخ‌ها', en: 'Clear dates' },
  regionFilter: { fa: 'ناحیه پوست سر', en: 'Scalp region' },
  regionFilterHint: { fa: 'برای محدود کردن تصاویر، یک ناحیه را انتخاب کنید.', en: 'Choose a region to narrow the gallery results.' },
  allRegions: { fa: 'نمایش همه نواحی', en: 'Show all regions' },
  allRegionsHint: { fa: 'بدون فیلتر ناحیه — همه تصاویر نمایش داده می‌شوند', en: 'No region filter — show images from every region' },
  imageSize: { fa: 'اندازه تصویر', en: 'Image size' },
  small: { fa: 'کوچک', en: 'Small' },
  large: { fa: 'بزرگ', en: 'Large' },
  noCompletedTrainingPhotos: { fa: 'تصویر تکمیل‌شده‌ای وجود ندارد', en: 'No completed training images' },
  loading: { fa: 'در حال بارگذاری...', en: 'Loading...' },
  trainingGalleryHint: {
    fa: 'عکس‌های این استخر به هیچ مشتری واقعی تعلق ندارند و فقط برای برچسب‌گذاری/آموزش مدل محلی استفاده می‌شوند.',
    en: 'Photos in this pool are not linked to any real client and are used only for labeling/training the local model.',
  },
  addTrainingPhotos: { fa: 'افزودن عکس', en: 'Add photos' },
  uploadingPhotos: { fa: 'در حال آپلود...', en: 'Uploading...' },
  noTrainingPhotos: { fa: 'هنوز عکسی در این استخر نیست', en: 'No photos in this pool yet' },
  runOfflineAnalysis: { fa: 'تحلیل آفلاین', en: 'Offline analysis' },
  runOnlineAnalysis: { fa: 'تحلیل آنلاین', en: 'Online analysis' },
  runExpertAnalysis: { fa: 'برچسب متخصص', en: 'Expert label' },
  deletePhoto: { fa: 'حذف عکس', en: 'Delete photo' },
  offlineAnalysisFailed: { fa: 'تحلیل آفلاین ناموفق بود', en: 'Offline analysis failed' },
  onlineAnalysisFailed: { fa: 'تحلیل آنلاین ناموفق بود', en: 'Online analysis failed' },
  selectRegionBeforeUpload: {
    fa: 'برای برچسب ناحیه اختیاری، ابتدا یک ناحیه انتخاب کنید یا مستقیم آپلود کنید',
    en: 'Optionally pick a region tag first, or upload directly without one',
  },
  trainingSampleSaved: { fa: 'نمونهٔ آموزشی ذخیره شد', en: 'Training sample saved' },
  apiKeyRequiredForOnline: {
    fa: 'ابتدا کلید API هوش مصنوعی را در تنظیمات وارد کنید',
    en: 'Configure an AI API key in Settings first',
  },
  noRegionTag: { fa: 'بدون برچسب ناحیه', en: 'No region tag' },
} as const satisfies Dict;
